#pragma once
//Texture Perturb Sin Wave
//UV Texture GET
int textureID = 14;
float2 uv = GetDefaultSceneTextureUV(Parameters, textureID);
//search texture map
float3 edgeMap = SceneTextureLookup(uv,textureID,false).rgb;
//chromatic aberration process
float2 aberrationAmount = float2(sin(uv.x),sin(uv.y));

float3 outputColor;
outputColor.r = SceneTextureLookup(uv+aberrationAmount,textureID,false).r;
outputColor.g = SceneTextureLookup(uv,textureID,false).g;
outputColor.b = SceneTextureLookup(uv-aberrationAmount,textureID,false).b;
//offset should be sin wave
return outputColor;
